name: flutter_application_00
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  smooth_page_indicator: ^1.0.0+2
  flutter:
    sdk: flutter
  get_storage: ^2.0.3
  country_code_picker: ^2.0.2
  flutter_otp_text_field: ^1.1.1
  flutter_screenutil: ^5.6.0
  carousel_slider: ^4.2.1
  getwidget: ^3.0.1
  scaled_list: ^2.0.0
  dotted_border: 2.0.0+3
  google_fonts: ^4.0.1
  flutter_svg: ^1.1.6
  pin_code_fields: ^7.4.0
  mj_image_slider: ^0.0.7
  clipboard: ^0.1.3
  flutter_image_slideshow: ^0.1.4
  flutter_custom_tab_bar: ^1.2.1
  # persistent_bottom_nav_bar: ^5.0.2
  velocity_x: ^3.6.0
  intl_phone_number_input: ^0.7.2
  intl_phone_field: ^3.1.0
  # video_viewer: ^1.2.7
  native_device_orientation: ^1.1.4
  dio: ^4.0.6
  freezed_annotation: ^2.2.0
  flutter_spinkit: ^5.1.0
  flutter_animation_progress_bar: ^2.3.1
  circle_progress_bar: ^0.1.2

dev_dependencies:
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

flutter:
  fonts:
    - family: Kadwa
      fonts:
        - asset: assets/fonts/Kadwa-Regular.ttf
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
