name: flutter_application_00
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:

  //-- 26-Jan-2023 --Ruchika --//
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  linear_progress_bar: ^1.1.0
  im_stepper: ^1.0.1+1
  step_progress_indicator: ^1.0.2
  //-----//
  get: 4.6.5
  smooth_page_indicator: ^1.0.0+2
  flutter:
    sdk: flutter
  get_storage: ^2.0.3
  country_code_picker: ^2.0.2
  flutter_otp_text_field: ^1.1.1
  flutter_screenutil: ^5.6.0
  carousel_slider: ^4.2.1
  chewie: ^1.3.6
  video_player: ^2.4.10

  scaled_list: ^2.0.0

  google_fonts: ^3.0.1


dev_dependencies:
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
