import 'package:ekinch/app/modules/job/form/controllers/job.controller.dart';
import 'package:ekinch/app/modules/postjob/controllers/postjob_controller.dart';
import 'package:ekinch/app/modules/postjob/views/widget/select_skills.dart';
import 'package:ekinch/widgets/snack_bar.dart';
import 'package:flutter/material.dart';
import 'package:ekinch/app/modules/postjob/Style.dart';
import 'package:ekinch/app/modules/postjob/views/post_job_view/CompanyDetails.dart';
import 'package:ekinch/app/modules/postjob/widgets/shortDropDown.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';
// import 'package:flutter_multiselect/flutter_multiselect.dart';

import '../../../../custom_widget/font_size.dart';

class JobDescriptions extends StatefulWidget {
  const JobDescriptions({Key? key}) : super(key: key);

  @override
  _JobDescriptionsState createState() => _JobDescriptionsState();
}

class _JobDescriptionsState extends State<JobDescriptions> {
  PostjobController controller = Get.put(PostjobController());
  int _count = 0;
  bool list1 = false;
  bool list2 = false;
  bool list3 = false;
  bool list4 = false;
  bool list5 = false;
  bool list6 = false;
  bool list7 = false;

  List skill = [
    "Leakage current detection",
    "Geyser connection",
    "Fixtures installation",
    "Three phase connection",
    "Knowledge about DC",
    "Two way switch",
    "Knowledge about HT panels",
    "Switch board fixing",
    "Horizontal & vertical chiselling",
    "Cove lightning work",
    "Fridge & washing machine connection",
    "AC connection",
    "Lightening arrester work",
    "Two phase connection",
    "Knowledge about AC",
    "One way switch",
    "knowledge about LT panels",
    "Conduit placement in false ceiling",
    "Knowledge of series & parallel network",
    "Decorative light fixture installation",
    "Lift connection",
    "Detection of shot circuiting",
    "Knowledge of wire,cable,switch,MCB,CCB,Fuse,Meter etc.",
    "Distribution board fixing",
    "Conduit placement in RCC Slab, wall",
    "Knowledge of drawing reading",
    "vertical aligment",
    "Bar binding at different angles",
    "Machine binding",
    "Chair making knowledge",
    "Drwaing reading",
    "Erection of bars",
    "Stirrups cutting & making",
    "Hand cutting work",
    "steel bar checking knowledge",
    "steel bar measurement work",
    "Horizontal bar alignment",
    "Placement of bars",
    "Hand bar binding",
    "Machine cutting",
    "Lap length knowledge",
    "Steel bar straightening work",
    "Safety knowledge (site)",
    "Hand cutting work",
    "Plate welding work",
    "Welding checking",
    "Fastner drilling & fixing",
    "Rod welding",
    "drawing reading",
    "Drawing checking",
    "MS Straightening work",
    "Mechanical cutting work",
    "Gas cutting",
    "Hold fast fabrication",
    "Gate Fabrication",
    "Steel welding",
    "Gas welding",
    "Cast iron work",
    "Fillet welding work",
    "Repair work",
    "Railing fabrication",
    "Material checking",
    "Spot welding",
    "Argon welding",
    "Measurement work",
    "Beading work",
    "Veneer pasting",
    "Wardrobe work",
    "Lock fixing",
    "Wood Adhesive work",
    "Wood finshing work",
    "Drawing checking",
    "Jali fixing work",
    "Dressing Table work",
    "Latch fixing",
    "Wood grinding work",
    "Wood Jointing work",
    "Wood sawing work",
    "Leveling work",
    "Glass fixing work",
    "Bed making work",
    "Hinges fixing",
    "Tower bolt fixing",
    "Mica pasting work",
    "Pattern painting",
    "Wood cutting",
    "Measurement work",
    "Duco painting",
    "Lacquer polishing",
    "Interior painting",
    "Texture Painting",
    "PVC Polishing",
    "Cleaning work",
    "Polishing (natural)",
    "Exterior painting",
    "Roller painting work",
    "Putty work",
    "Paint material checking",
    "Satin painting",
    "Melamine polishing",
    "Ground panting",
    "Pattern painting",
    "Machine sanding",
    "Sanding",
    "Material checking",
    "Drawing checking",
    "Drawing reading",
    "Sewer chamber construction work",
    "Geyser installation",
    "Bottle trap fixing",
    "Jointing work",
    "Levelling work",
    "Repairing work",
    "Spout fixing",
    "WC fixing",
    "Threading work",
    "Water leakage checking",
    "Water tank fixing",
    "Water tap fixing",
    "Pipe fitting",
    "Core cutting",
    "Repair work",
    "Concrete work",
    "Plastering work",
    "Steel work",
    "Levelling work",
    "Ground filling",
    "Shuttering work",
    "Stone work",
    "Brick work",
    "Construction Material checking",
    "Grouting work",
    "Damp Proofing work",
    "RCC work",
    "Tile Work",
    "Measurement work",
  ];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: whitedark,
      body: Padding(
        padding: EdgeInsets.all(15.0),
        child: ListView(
          shrinkWrap: true,
          // crossAxisAlignment: CrossAxisAlignment.start,
          //    mainAxisAlignment: MainAxisAlignment.start,
          children: [
            Text(
              'Location',
              style: GoogleFonts.kadwa(
                fontSize: F18(),
                fontWeight: FontWeight.w700,
                color: black,
              ),
            ),
            SizedBox(
              height: MediaQuery.of(context).size.height * 0.002,
            ),
            DropdownFieldFull(
              controller: controller.address,
              hintText: "Select Location",
              items: const [
                "Agra",
                "Ahmedabad",
                "Ajmer",
                "Akola",
                "Aligarh",
                "Allahabad",
                "Alwar",
                "Amravati",
                "Amritsar",
                "Anand",
                "Anantapur",
                "Arrah",
                "Asansol",
                "Aurangabad",
                "Avadi",
                "Bally",
                "Bangalore",
                "Baranagar",
                "Barasat",
                "Bardhaman",
                "Bareilly",
                "Bathinda",
                "Begusarai",
                "Belgaum",
                "Bellary",
                "Berhampur",
                "Bhagalpur",
                "Bharatpur",
                "Bhatpara",
                "Bhilai",
                "Bhilwara",
                "Bhiwandi",
                "Bhopal",
                "Bhubaneswar",
                "Bhusawal",
                "Bidar",
                "Bihar Sharif",
                "Bijapur",
                "Bikaner",
                "Bilaspur",
                "Bokaro",
                "Brahmapur",
                "Budaun",
                "Bulandshahr",
                "Burhanpur",
                "Chandausi",
                "Chandigarh",
                "Chandrapur",
                "Chapra",
                "Chennai",
                "Chinsurah",
                "Coimbatore",
                "Cuttack",
                "Daman",
                "Darbhanga",
                "Darjiling",
                "Davanagere",
                "Dehra Dun",
                "Dehri",
                "Delhi",
                "Deoghar",
                "Dewas",
                "Dhanbad",
                "Dhule",
                "Dibrugarh",
                "Dimapur",
                "Dindigul",
                "Durg",
                "Durgapur",
                "Ernakulam",
                "Erode",
                "Faridabad",
                "Gandhidham",
                "Gandhinagar",
                "Gangtok",
                "Ghaziabad",
                "Giridih",
                "Goa",
                "Gorakhpur",
                "Gulbarga",
                "Guntur",
                "Gurgaon",
                "Guwahati",
                "Gwalior",
                "Hajipur",
                "Haldia",
                "Haldwani",
                "Hapur",
                "Haridwar",
                "Hassan",
                "Himatnagar",
                "Hindupur",
                "Hisar",
                "Hooghly",
                "Hoshiarpur",
                "Howrah",
                "Hubli",
                "Hyderabad",
                "Idukki",
                "Imphal",
                "Indore",
                "Jabalpur",
                "Jagdalpur",
                "Jaipur",
                "Jalandhar",
                "Jalgaon",
                "Jammu",
                "Jamnagar",
                "Jamshedpur",
                "Jhansi",
                "Jodhpur",
                "Junagadh",
                "Kadapa",
                "Kakinada",
                "Kalyan",
                "Kancheepuram",
                "Kannur",
                "Kanpur",
                "Kanyakumari",
                "Karimnagar",
                "Karnal",
                "Karur",
                "Khammam",
                "Khanna",
                "Kharagpur",
                "Kochi",
                "Kodaikanal",
                "Kolar",
                "Kolhapur",
                "Kolkata",
                "Kollam",
                "Kota",
                "Kottayam",
                "Kozhikode",
                "Krishnagiri",
                "Kullu",
                "Kurnool",
                "Kurukshetra",
                "Latur",
                "Lucknow",
                "Ludhiana",
                "Madikeri",
                "Madurai",
                "Mahabalipuram",
                "Mahbubnagar",
                "Mahe",
                "Malerkotla",
                "Mangalore",
                "Manipal",
                "Mapusa",
                "Margao",
                "Mathura",
                "Medak",
                "Meerut",
                "Mirzapur",
                "Mohali",
                "Moradabad",
                "Motihari",
                "Mount Abu",
                "Muktsar",
                "Mumbai",
                "Munger",
                "Murshidabad",
                "Muzaffarnagar",
                "Muzaffarpur",
                "Mysore",
                "Nadiad",
                "Nagercoil",
                "Nagpur",
                "Nainital",
                "Nalgonda",
                "Namakkal",
                "Nanded",
                "Nashik",
                "Navsari",
                "Neemuch",
                "Nellore",
                "New Delhi",
                "Nizamabad",
                "Noida",
                "Ongole",
                "Osmanabad",
                "Palakkad",
                "Palampur",
                "Palghar",
                "Pali",
                "Palwal",
                "Panaji",
                "Panchkula",
                "Panipat",
                "Panvel",
                "Raipur",
                "Rajkot",
                "Rajahmundry",
                "Rajnandgaon",
                "Ranchi",
                "Rangareddy",
                "Ratlam",
                "Ratnagiri",
                "Raurkela",
                "Rewa",
                "Rewari",
                "Rohtak",
                "Rohtas",
                "Rudraprayag",
                "Rupnagar",
                "Sabarkantha",
                "Sagar",
                "Saharanpur",
                "Saharsa",
                "Salem",
                "Samastipur",
                "Samba",
                "Sambalpur",
                "Sangli",
                "Sangrur",
                "Sant Kabir Nagar",
                "Sant Ravidas Nagar",
                "Saran",
                "Satara",
                "Satna",
                "Sawai Madhopur",
                "Sehore",
                "Senapati",
                "Seoni",
                "Seraikela Kharsawan",
                "Serchhip",
                "Shahdol",
                "Shahjahanpur",
                "Shajapur",
                "Shamli",
                "Sheikhpura",
                "Sheohar",
                "Sheopur",
                "Shimla",
                "Shimoga",
                "Shivamogga",
                "Shivpuri",
                "Shopian",
                "Shravasti",
                "Siddharthnagar",
                "Sidhi",
                "Sikar",
                "Simdega",
                "Sindhudurg",
                "Singrauli",
                "Sirmaur",
                "Sirohi",
                "Sirsa",
                "Sitamarhi",
                "Sitapur",
                "Sivaganga",
                "Siwan",
                "Solan",
                "Solapur",
                "Sonbhadra",
                "Sonipat",
                "Sonitpur",
                "South Andaman",
                "South Delhi",
                "South Garo Hills",
                "South Goa",
                "South Salmara Mankachar",
                "South Tripura",
                "Srikakulam",
                "Srinagar",
                "Subarnapur",
                "Sukma",
                "Sultanpur",
                "Sundargarh",
                "Supaul",
                "Surat",
                "Surendranagar",
                "Surguja",
                "Tamenglong",
                "Tarn Taran",
                "Tawang",
                "Tehri Garhwal",
                "Thane",
                "Thanjavur",
                "The Dangs",
                "Theni",
                "Thiruvananthapuram",
                "Thoothukudi",
                "Thoubal",
                "Thrissur",
                "Tikamgarh",
                "Tinsukia",
                "Tirap",
                "Tiruchirappalli",
                "Tirunelveli",
                "Tiruppur",
                "Tiruvallur",
                "Tiruvannamalai",
                "Tonk",
                "Tuensang",
                "Tumkur",
                "Uchgaon",
                "Udaipur",
                "Udaipurwati",
                "Udgir",
                "Udhagamandalam",
                "Udhampur",
                "Udumalaipettai",
                "Udupi",
                "Ujhani",
                "Ujjain",
                "Ulhasnagar",
                "Uluberia",
                "Una",
                "Unjha",
                "Unnamalaikadai",
                "Unnao",
                "Upleta",
                "Uran",
                "Uravakonda",
                "Urmar Tanda",
                "Usilampatti",
                "Uthamapalayam",
                "Uthiramerur",
                "Utraula",
                "Vadakkuvalliyur",
                "Vadalur",
                "Vadgaon Kasba",
                "Vadipatti",
                "Vadnagar",
                "Vadodara",
                "Vaijapur",
                "Vaikom",
                "Valparai",
                "Valsad",
                "Vandavasi",
                "Vaniyambadi",
                "Vapi",
                "Varanasi",
                "Varkala",
                "Vasai-Virar",
                "Vatakara",
                "Vedaranyam",
                "Vellakoil",
                "Vellore",
                "Venkatagiri",
                "Veraval",
                "Vidisha",
                "Vijapur",
                "Vijayapura",
                "Vijayawada",
                "Vijaypur",
                "Vikarabad",
                "Vikramasingapuram",
                "Viluppuram",
                "Vinukonda",
                "Viramgam",
                "Virudhachalam",
                "Virudhunagar",
                "Visakhapatnam",
                "Visnagar",
                "Viswanatham",
                "Vita",
                "Vizianagaram",
                "Vrindavan",
                "Vyara",
                "Wadgaon Road",
                "Wadhwan",
                "Wadi",
                "Wai",
                "Wanaparthy",
                "Wani",
                "Wankaner",
                "Warangal",
                "Wardha",
                "Warhapur",
                "Warisaliganj",
                "Warora",
                "Warud",
                "Washim",
                "Wokha",
                "Yadgir",
                "Yamunanagar",
                "Yanam",
                "Yavatmal",
                "Yawal",
                "Yellandu",
                "Yemmiganur",
                "Yerraguntla",
                "Yevla",
                "Zaidpur",
                "Zamania",
                "Zira",
                "Zirakpur",
                "Zunheboto"
              ],
            ),
            SizedBox(
              height: MediaQuery.of(context).size.height * 0.012,
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  'Skills for the Job',
                  style: GoogleFonts.kadwa(
                    fontSize: F18(),
                    fontWeight: FontWeight.w700,
                    color: black,
                  ),
                ),
                Text(
                  'Add',
                  style: GoogleFonts.kadwa(
                    fontSize: F18(),
                    fontWeight: FontWeight.w700,
                    color: black,
                  ),
                ),
              ],
            ),

            SizedBox(
              height: MediaQuery.of(context).size.height * 0.002,
            ),

            Wrap(
              clipBehavior: Clip.antiAlias,
              alignment: WrapAlignment.start,
              direction: Axis.horizontal,
              children: (skill)
                  .sublist(0, 10)
                  .map((e) => SelectSkillCard(
                        title: e,
                      ))
                  .toList(),
            ),
            Visibility(
              visible: list1,
              child: Wrap(
                alignment: WrapAlignment.start,
                direction: Axis.horizontal,
                children: (skill)
                    .sublist(11, 40)
                    .map((e) => SelectSkillCard(
                          title: e,
                        ))
                    .toList(),
              ),
            ),
            Visibility(
              visible: list2,
              child: Wrap(
                alignment: WrapAlignment.start,
                direction: Axis.horizontal,
                children: (skill)
                    .sublist(41, 60)
                    .map((e) => SelectSkillCard(
                          title: e,
                        ))
                    .toList(),
              ),
            ),
            Visibility(
              visible: list3,
              child: Wrap(
                alignment: WrapAlignment.start,
                direction: Axis.horizontal,
                children: (skill)
                    .sublist(61, 85)
                    .map((e) => SelectSkillCard(
                          title: e,
                        ))
                    .toList(),
              ),
            ),
            Visibility(
              visible: list4,
              child: Wrap(
                alignment: WrapAlignment.start,
                direction: Axis.horizontal,
                children: (skill)
                    .sublist(86, 120)
                    .map((e) => SelectSkillCard(
                          title: e,
                        ))
                    .toList(),
              ),
            ),
            Visibility(
              visible: list5,
              child: Wrap(
                alignment: WrapAlignment.start,
                direction: Axis.horizontal,
                children: (skill)
                    .sublist(121, 136)
                    .map((e) => SelectSkillCard(
                          title: e,
                        ))
                    .toList(),
              ),
            ),

            Column(
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                //  SelectSkill(context, controller)
                InkWell(
                  onTap: () {
                    _count++;
                    setState(() {
                      switch (_count) {
                        case 1:
                          list1 = true;
                          break;
                        case 2:
                          list2 = true;
                          break;
                        case 3:
                          list3 = true;
                          break;
                        case 4:
                          list4 = true;
                          break;
                        case 5:
                          list5 = true;
                          break;
                        case 6:
                          list6 = true;
                          break;
                        case 7:
                          list7 = true;
                          break;
                        case 8:
                          errorSnackbar("No more skills");
                      }
                    });
                  },
                  child: Text(
                    'Load More +',
                    style: GoogleFonts.kadwa(
                      fontSize: F18(),
                      fontWeight: FontWeight.w700,
                      color: black,
                    ),
                  ),
                ),
              ],
            ),
            SizedBox(
              height: MediaQuery.of(context).size.height * 0.02,
            ),
            Text(
              'Describe the Job Role',
              style: GoogleFonts.kadwa(
                fontSize: F18(),
                fontWeight: FontWeight.w700,
                color: black,
              ),
            ),
            SizedBox(
              height: MediaQuery.of(context).size.height * 0.002,
            ),
            SizedBox(
              height: 80,
              child: Description(
                controller: controller.description,
                hintText: 'Please Describe here',
                initialValue: 'Please Describe here',
              ),
            ),
            SizedBox(
              height: MediaQuery.of(context).size.height * 0.02,
            ),
            Text(
              'Job Timing',
              style: GoogleFonts.kadwa(
                fontSize: F18(),
                fontWeight: FontWeight.w700,
                color: black,
              ),
            ),
            SizedBox(
              height: MediaQuery.of(context).size.height * 0.002,
            ),
            DropdownFieldFull(
              controller: controller.jobTmg,
              hintText: "Select Job Timming",
              items: const[
                '1:00 am - 10:00 am',
                '2:00 am - 11:00 am',
                '3:00 am - 12:00 pm',
                '4:00 am - 1:00 pm',
                '5:00 am - 2:00 pm',
                '6:00 am - 3:00 pm',
                '7:00 am - 4:00 pm',
                '8:00 am - 5:00 pm',
                '9:00 am - 6:00 pm',
                '10:00 am - 7:00 pm',
                '11:00 am - 8:00 pm',
                '12:00 pm - 9:00 pm',
                '1:00 pm -10:00 pm',
                '2:00 pm - 11:00 pm',
                '3:00 pm - 12:00 am',
                '4:00 pm - 1:00 am',
                '5:00 pm - 2:00 am',
                '6:00 pm - 3:00 am',
                '7:00 pm - 4:00 am',
                '8:00 pm - 5:00 am',
                '9:00 pm - 6:00 am',
                '10:00 pm - 7:00 am',
                '11:00 pm - 8:00 am',
                '12:00 pm - 9:00 am',
              ],
            ),
            SizedBox(
              height: MediaQuery.of(context).size.height * 0.02,
            ),
            // Text(
            //   'Interview Timing',
            //   style: GoogleFonts.kadwa(
            //     fontSize: F18(),
            //     fontWeight: FontWeight.w700,
            //     color: black,
            //   ),
            // ),
            // SizedBox(
            //   height: MediaQuery.of(context).size.height * 0.002,
            // ),
            // DropdownFieldFull(
            //   controller: controller.interviewTime,
            //   hintText: "Select Interview Timming",
            //   items: [
            //     '9:00 am - 6:00 pm  |  Mon to Sat',
            //     '10:00 am - 7:00 pm  |  Mon to Sat',
            //     '11:00 am - 8:00 pm  |  Mon to Sat',
            //   ],
            // ),
            // SizedBox(
            //   height: MediaQuery.of(context).size.height * 0.03,
            // ),
            // Material(
            //     borderRadius: BorderRadius.circular(10.0),
            //     color: yellow,
            //     child: MaterialButton(
            //         minWidth: MediaQuery.of(context).size.width,
            //         onPressed: () {
            //         //  Get.to(CompanyDetails());
            //         },
            //         child: Center(
            //           child: Text(
            //             'Next',
            //             style: GoogleFonts.kadwa(
            //                 color: black,
            //                 fontSize: 18,
            //                 fontFamily: 'Kadwa',
            //                 fontWeight: FontWeight.w700),
            //           ),
            //         ))),
          ],
        ),
      ),
    );
  }
}
